CXX=g++
CPPFLAGS=--std=c++17 -lpthread

helloWorld: helloWorld.cpp
	${CXX} ${CPPFLAGS} -o helloWorld helloWorld.cpp

helloWorldMultiple: helloWorldMultiple.cpp
	${CXX} ${CPPFLAGS} -o helloWorldMultiple helloWorldMultiple.cpp

clean: 
	rm -f *.o helloWorld helloWorldMultiple